feat: remove mark for deletion logic
smartprocure/contexture-client pull request #136
Opened 2020-09-23 20:52 UTC by ccalbaugh

This PR removes the marking and subsequent deletion of nodes with no value during tree serialization.

2020-09-23 20:54 UTC, decrapifier commented
<!--
  0 failure: 
  2 warning:  Branch being merg..., The README has no...
  2 messages
  
  DangerID: danger-id-default;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Branch being merged does not follow [Git Flow](http://nvie.com/posts/a-successful-git-branching-model/)
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>The README has not been updated. Please update the README.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>You reduced the total lines of code! Awesome! :+1:</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>Could not find any browser results.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 807506ba0c7805ae22a212f9e8ef796f56b79715
</p>

2020-09-23 21:27 UTC, rma4ok approved these changes
Looks good to me!

2020-09-25 00:13 UTC, daedalus28 requested changes

2020-09-25 00:13 UTC, daedalus28 commented on src/serialize.js
> +              x.children
While we're at it, I think we should just eliminate *all* node deletion by the client - leaving in the code that wipes empty groups still makes the returned tree not necessarily match up in index order

2020-10-30 03:54 UTC, daedalus28 requested changes
You also need to update the readme to remove mentions of this behavior. It's definitely in the "process algorithm" section and might be in other places

2020-10-30 14:22 UTC, daedalus28 approved these changes

2020-10-30 14:23 UTC, merged