Add onSerialize hook
smartprocure/contexture-client pull request #187
Opened 2022-09-01 17:40 UTC by stellarhoof

2022-09-01 17:41 UTC, decrapifier commented
<!--
  1 failure:  Please add a desc...
  2 warning:  The README has no..., You should add at...
  1 messages
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Please add a description to your PR</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>The README has not been updated. Please update the README.</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>You should add at least 1 more reviewer to the PR</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Could not find any browser results.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9a34d8c0e9914a4100ed5d2988e5e04ce6a0d22d
</p>

2022-09-01 18:00 UTC, decrapifier commented
<!--
  0 failure: 
  1 warning:  The README has no...
  1 messages
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>The README has not been updated. Please update the README.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Could not find any browser results.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f55ac01de6a4c297d9da0c8285cec3fab62294ab
</p>

2022-09-01 19:21 UTC, daedalus28 requested changes

2022-09-01 19:21 UTC, daedalus28 commented on src/serialize.js
> +  Tree.map(({ onSerialize = _.identity, ...x }) => {
onSerialize should pull from the type definition, not specific nodes

2022-09-02 15:10 UTC, dshishkov approved these changes

2022-09-02 21:53 UTC, merged